# Generated by Django 2.1 on 2019-05-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='last_session_key',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
