# Generated by Django 2.1 on 2020-10-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_auto_20190530_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='num_visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
